fix(utils): Allows numbers as strings
StefH/angular-odata-es5 pull request #30
Opened 2017-11-05 05:18 UTC by markwaddle

Currently numeric strings are serialized as numbers to function parameters. This is not always the desired behavior. Sometimes you just want a string with digits in it. 😄 

This changes the behavior so that strings are strings and numbers are numbers.

Additionally this properly escapes single quotes in strings.

2017-11-05 10:04 UTC, StefH requested changes
Thanks ! Can you take a look at my comments?

2017-11-05 10:04 UTC, StefH commented on src/angularODataConfiguration.ts
> +    public getEntityUri(entityKey: string | number, typeName: string): string {
Also add ` | boolean` here?

2017-11-05 10:04 UTC, StefH commented on test/angularODataUtils.spec.ts
>      it('quoteValue integer', () => {
Can you please also add a test for boolean?

Like:
`it('quoteValue boolean', () => {`

2017-11-05 17:31 UTC, markwaddle commented
You're welcome! I completed the changes you requested

2017-11-06 06:53 UTC, StefH approved these changes

2017-11-06 06:54 UTC, merged