feat(function): Add methods CustomCollectionAction, CustomCollectionF…
StefH/angular-odata-es5 pull request #45
Opened 2018-01-31 14:36 UTC by bastienlemaitre

Add methods CustomCollectionAction, CustomCollectionFunction and support for Apply.

I've tried to create others tests but i dont know if your api contains CollectionActions and CollectionFunctions.

It match the Microsoft's tutorial about Functions & Actions for OData V4:
https://blogs.msdn.microsoft.com/odatateam/2014/12/08/tutorial-sample-functions-actions-in-web-api-v2-2-for-odata-v4-0-type-scenario/

2018-01-31 15:02 UTC, StefH requested changes
I did add a code-review comment which solves some/all failures in the unit-tests.

Can you take a look ?

2018-01-31 15:02 UTC, StefH commented on src/angularODataQuery.ts
> +    private _apply: string[];
Init an empty array here, else the unit-tests fail.

``` javascript
private _apply: string[] = [];
```

2018-01-31 15:38 UTC, StefH requested changes

2018-01-31 15:38 UTC, StefH commented on test/angularODataQuery.spec.ts
> +        assert.equal(test['_apply'], ['groupby((LastName))']);
use `deepEqual`

2018-01-31 18:24 UTC, StefH commented
I've added some code-review comments, can you take a look?

2018-01-31 18:43 UTC, bastienlemaitre commented
Fixed

2018-01-31 18:48 UTC, bastienlemaitre commented
Can you add methods on your api like this tutorial ? After I will add more units tests.
https://blogs.msdn.microsoft.com/odatateam/2014/12/08/tutorial-sample-functions-actions-in-web-api-v2-2-for-odata-v4-0-type-scenario/

2018-01-31 18:55 UTC, StefH requested changes
You have replaced/removed the tests for
Custom Function 1
Custom Function 2
Custom Function with parameters

Please add these again.

2018-01-31 18:55 UTC, StefH commented
You have replaced/removed the tests for
Custom Function 1
Custom Function 2
Custom Function with parameters

Please add these again.

2018-01-31 19:34 UTC, bastienlemaitre commented
They can't be added again, i've updated the method CustomFunction because it wasn't adapted to the Microsoft's tutorial.
The next url
```url
http://localhost/odata/Employees/getSalesTaxRate(area='abc', postalCode=10)
```
is a CustomCollectionFunction not a Custom function.
But the next url
```url
http://localhost/odata/Employees(12)/getSalesTaxRate(area='abc', postalCode=10)
```
is a CustomFunction.
That's why you need to add more availables urls to fix unit tests.

2018-01-31 19:50 UTC, bastienlemaitre commented
Fixed

2018-01-31 19:52 UTC, StefH commented
One more request: this line is not tested:
https://codecov.io/gh/StefH/angular-odata-es5/compare/c0cc4519309ff239edd29742a643c8a21f0d4617...c29f052f554dc6163aeac309aa9f7fb8b3985f82/src/src/angularODataQuery.ts?before=src/angularODataQuery.ts#L124

A solution for this is adding a `it('Exec' . . . ` test in the file `odataAngularQuery.spec.ts` which tests this new Apply code

2018-01-31 20:14 UTC, bastienlemaitre commented
Fixed

2018-01-31 21:20 UTC, bastienlemaitre commented
Can you merge it ?

2018-02-01 08:56 UTC, StefH commented
I'll merge it in some time.

2018-02-02 11:32 UTC, bastienlemaitre commented
Sorry to be insistent but I absolutely need it for my work. No chance to merge?

2018-02-02 11:49 UTC, StefH approved these changes

2018-02-02 11:49 UTC, merged

2018-02-02 11:54 UTC, StefH commented
Version 0.2.8 is added to npmjs.

2018-02-02 12:44 UTC, bastienlemaitre commented
Thank you !