fix: return correct url if entity name is empty
StefH/angular-odata-es5 pull request #86
Opened 2020-01-29 12:17 UTC by pleshakovalexander

Can be useful in case calling method without entity

2020-01-29 18:29 UTC, StefH requested changes
see comments...

2020-01-29 18:29 UTC, StefH commented on src/angularODataConfiguration.ts
> +        if(typeName){
Please do a format file.

2020-01-29 18:29 UTC, StefH commented on src/angularODataConfiguration.ts
>      public getEntitiesUri(typeName: string): string {
And update / add a unit-test

2020-01-29 19:26 UTC, pleshakovalexander commented on src/angularODataConfiguration.ts
> +        if(typeName){
@StefH done

2020-01-29 19:26 UTC, pleshakovalexander commented on src/angularODataConfiguration.ts
>      public getEntitiesUri(typeName: string): string {
@StefH done

2020-02-11 07:03 UTC, StefH approved these changes

2020-02-22 09:05 UTC, merged