feat(CustomParams): Added support for custom query parameters
StefH/angular-odata-es5 pull request #92
Opened 2020-02-27 13:26 UTC by axeltaylor

Adds support to provide custom query parameters.
Also closes #70

2020-03-04 10:34 UTC, albert-asin commented
I need this new feature in my project
It looks great and could solve my problem
thanks for the idea

2020-03-04 10:41 UTC, axeltaylor commented
> I need this new feature in my project
> It looks great and could solve my problem
> thanks for the idea

@StefH what do you think?

2020-03-04 10:49 UTC, StefH approved these changes

2020-03-04 10:50 UTC, StefH commented
the code + unit tests look fine

I'm not sure if this is 100% odata compatible, but if it helps you, I will publish a new version this week

2020-03-04 11:06 UTC, axeltaylor commented
Thank you @StefH , regarding the odata compatibility I found this information in the specification:  http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_CustomQueryOptions

It seems that is allowed and compatible but maybe we should add logic to not allow parameters starting with $ or @ characters. 
> Custom query options MUST NOT begin with a $ or @ character.

What do you think?

2020-03-04 18:11 UTC, StefH commented
Good investigation.

I think it's good to verify the parameters for $ and @, and throw exception when the value is invalid.

2020-03-12 07:28 UTC, StefH commented on src/angularODataQuery.ts
> +        if (key.indexOf('$') === 0 || key.indexOf('@') === 0) {
I think this method cannot handle undefined/null `key` ? Maybe add a null/undefined check?

2020-03-12 07:29 UTC, StefH requested changes
Looks good.
Please take a look at my comment; I'm not sure if this applies..

2020-03-29 18:07 UTC, illustriousmuz commented
Hi, this would be a very useful feature for a project I'm currently working on. Any ETA for a release? Thanks

2020-03-29 20:54 UTC, StefH approved these changes
Thank you

2020-03-29 20:54 UTC, StefH commented
@albert-asin and @illustriousmuz  : new version will be available in some hours

2020-03-29 20:55 UTC, merged